Insert, Move, and Delete within BootOrder
rhboot/efibootmgr pull request #132
Opened 2020-05-09 20:19 UTC by bdk0

Provides the functionality from Issue #126

1) When adding a new entry with -c, optionally allow an Index to be
provided with -I. If no index is provided, it defaults to 1, which
inserts the new entry first in the boot order, and provides the
same functionality as previous versions. If -I is provided, it
specifies where in the BootOrder to insert the new entry. (If -I 2
is passed, the new entry will be inserted in the second place.)
If the index specified is greater than the number of entries in the
BootOrder, the entry is placed last.

2) In addition to modifying the BootOrder by passing an entire new
BootOrder as comma-delimted string to -o, two new formats are allowed:

   -o -5 will remove entry 5 (Boot0005) from the BootOrder string
   -o +5 will add entry 5 (Boot0005) to the BootOrder string.
         By default the entry will be added at the beginning of the
         BootOrder (in first place), but this behavior can be
         overridden by specifying an index with -I as above.
         If the specified entry already exists in the BootOrder,
         then it will be moved to the specified index.

2021-06-17 14:58 UTC, vathpela requested changes

2021-06-17 14:58 UTC, vathpela commented on README
> +        -I | --at-index        place BootOrder entry at specified index
This should be "--at-index index". But why not make this "--insert index" and have it imply "-c"?

2021-06-17 14:58 UTC, vathpela commented on README.md
> +        -I | --at-index        place BootOrder entry at specified index
Same questions as above; there's also a bunch of places below the same question would apply, so I won't mention them.

2021-06-17 14:58 UTC, vathpela commented on src/efibootmgr.c
> +            index=0;
This should to be `index = 0;`

2021-06-17 14:58 UTC, vathpela commented on src/efibootmgr.c
> +		errorx(3, "-I option must be used with -c option or -o option ");
Again, I'd rather just have it imply "-c", and not interact with "-o" at all.

2021-06-17 14:58 UTC, vathpela commented on src/efibootmgr.c
> +				ret = add_to_order(order_name[mode],result,opts.at_index-1);
Maybe conditionalize this on `if (ret >= 0 || ret == ENOENT)`?

2021-06-17 14:58 UTC, vathpela commented on src/efibootmgr.8.in
> +Place entry in BootOrder at specified index. 1 is beginning. If set to greater than number of entries in BootOrder, it will be placed last. (Defaults to 1)
Why is this 1-indexed?  That seems weird to me.

2021-06-18 01:27 UTC, bdk0 commented on src/efibootmgr.c
> +		errorx(3, "-I option must be used with -c option or -o option ");
Thank you, I'll go ahead and make all the suggested changes to the patch. 

 If '-o' no longer utilizes the index from '-I', the functionality to insert into the Boot Order at positions other than in first place, and the functionality to move existing Boot Order Entries to positions other than first place will be lost. Would you prefer to leave this functionality out of the patch all together? Or perhaps an alternative syntax to the -o command to optionally allow the index to be set directly ( something like -o +3:5 to insert or move Boot0003 to position 5) would be acceptable?

2022-04-01 20:38 UTC, closed without merging